name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: clair-de-lune
            asset_name: clair-de-lune-linux-amd64
          - os: windows-latest
            artifact_name: clair-de-lune.exe
            asset_name: clair-de-lune-windows-amd64.exe
          - os: macos-latest
            artifact_name: clair-de-lune
            asset_name: clair-de-lune-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
